export const dev = window.location.origin.includes('localhost')
export const baseURL = dev ? 'http://localhost:3000' : ''
export const servePath = dev ? '' : '/bookclub/'
export const useSockets = false
export const domain = 'dev-eux5v4apdr8nm4hz.us.auth0.com'
export const audience = 'https://jaredcarlson.dev'
export const clientId = 'ST0ooOcWbPuoU6Xz5THsB0e6GNn3U6OM'
export const gbak = 'AIzaSyBcf7Ry8H9mWxSzyfghzaS7sU0WN9Qxtj4'
export const ntak = 'NhL89IMsqCIzG7YABO2ybDtxKek7Mh1L'